machow/quartodoc

docs/.gitignore, examples/.gitignore, quartodoc/ast.py, quartodoc/renderers.py, quartodoc/tests/test_ast.py
* Adds support for narrowing DocstringSectionText to specific classes for "Warnings", and "Notes" (see https://github.com/machow/quartodoc/issues/34#issuecomment-1421248993)
* Refactors transformation logic to live in the `quartodoc.ast` submodule
* Adds basic tests of narrowing.
=> Feat narrow notes

quartodoc/renderers/md_renderer.py, quartodoc/tests/example_attribute.py, quartodoc/tests/test_basic.py
Begins work toward https://github.com/machow/quartodoc/issues/51, by enabling renderer to render Attribute objects (e.g. class attributes, module attributes).
=> feat: render attribute docs

quartodoc/autosummary.py, quartodoc/tests/example_dynamic.py, quartodoc/tests/test_basic.py
Addresses https://github.com/machow/quartodoc/issues/54, https://github.com/machow/quartodoc/issues/3, by adding a dynamic flag to get_object -- which allows you to dynamically load the exact docstring for a function.
=> feat: add dynamic option to get_object

quartodoc/ast.py
This PR fixes a recent issue, where patched docstring sections were missing their contents. For example, quartodoc adds in a custom DocstringNotesSection, whose `.value` was None in a vetiver docs build.
I think this is likely a regression, since there are already tests to cover this case. (I was able to fix the vetiver build with this change).
=> fix: patched docstrings missing their contents

quartodoc/autosummary.py, setup.cfg
This PR adds a log message from the Builder, when a page is written. This means that when people run `python -m quartodoc build --verbose`, they get feedback on what pages are re-written.
This is important because for sites with hundreds of pages, re-writing pages means waiting for quarto to re-render them.
=> ux: log when an api page is written

quartodoc/renderers/md_renderer.py, quartodoc/tests/example_signature.py, quartodoc/tests/test_renderers.py
This PR addresses #91 and #93 by ensuring the renderer always renders a signature with `*` or `**` for `*args` and `**kwargs`, respectively. Currently, it erroneously omits this if the renderer does not have show_signature_annotations set to True.
=> fix: always render *args and **kwargs in signature

Makefile, quartodoc/renderers/base.py, setup.cfg
Addresses #106, by creating a command line interface for quartodoc, e.g., from the shell:
```
quartodoc --help
quartodoc build --verbose
```
It uses the same mechanism as the `python -m quartodoc` approach, so behaviors should be identical. I should note that the `python -m ` approach sets the sys path to be the cwd, while the CLI approach sets it to be the bin directory (or something like that)
=> feat: add cli entrypoint

quartodoc/renderers/md_renderer.py, quartodoc/tests/example_signature.py, quartodoc/tests/test_renderers.py
Addresses #117, 
* ensures a lone `*, ` is *not* added to a signature when a varargs arg comes before a kw only arg
- e.g. `def f(a, *args, b)`
- e.g. `def f(a, *, b)`
* correctly render position only args (e.g. `def f(a, /): ...`)
* add tests of 4 common signature configurations
=> fix: better support for rendering /, and * in signatures

docs/_quarto.yml
This small PR fixes a couple pages being excluded because they were renamed
=> docs: fix misnamed page references

docs/get-started/docstring-examples.qmd
Fixes a small issue, where I didn't know how to escape a quarto block, so used a `\` as a placeholder.
See the quarto docs on escaping unexecuted blocks: https://quarto.org/docs/computations/execution-options.html#unexecuted-blocks
=> docs: correctly escape when mentioning quarto block

docs/get-started/overview.qmd
Replaces some old uses of `python -m quartodoc build`
=> docs: use quartodoc build for cli instructions

docs/get-started/docstring-examples.qmd
This PR adds some notes on documenting class docstrings, and points to the numpydoc section on it.
=> docs: how to document classes

examples/weird-install/_quarto.yml, examples/weird-install/src/some_module.py, quartodoc/autosummary.py
This PR adds support for loading source files from custom locations, when running `quartodoc build`. It adds a `source_dir` argument, that put a custom location onto `sys.path`.
Addresses #130
=> feat: Builder source_dir parameter for non-package loads

setup.cfg
Addresses https://github.com/machow/quartodoc/issues/169 by removing the python 3.8 tag from PyPI
=> dev: remove python 3.8 tag

quartodoc/ast.py, quartodoc/renderers/md_renderer.py, setup.cfg
This PR enables support for griffe v0.28 by changing imports for two classes that were moved...
```
from griffe.dataclasses import Name, Expression
from griffe.expressions import Name, Expression
```
Note that this ~~breaks backwards compatibility~~ (edit: nvm just used a try/except import) with previous versions of griffe, so we'll need to update the renderers in siuba and pyshiny.
=> fix: support griffe v0.28

quartodoc/autosummary.py, quartodoc/tests/example_dynamic.py, quartodoc/tests/test_basic.py
This PR fixes issues with loading classes (and their members) dynamically. Namely, it tries to gracefully fall back to static loading for instance and class variables with no values (which can't be loaded, because there's nothing there, but may have docstrings that can be loaded by sphinx/griffe).
This is part of progress toward
* #133
=> Fix dynamic class loading

Makefile, _extensions/interlinks/interlinks.lua, quartodoc/tests/example_interlinks/interlinks.lua, quartodoc/tests/example_interlinks/test.md
This PR addresses
* #176 
by wrapping interlink results in a code element.
Note that this only applies to links where the name is filled in from the inventory. So `` [my custom name](`get_object`) `` does *not* wrap `my custom name` in code, but `` [](`get_object`) `` does produce `get_object` wrapped in a code element. This is to ensure that users can link to objects without using code elements (they can still add the backticks manually if they want to).
=> feat: interlink link content now in a code element

quartodoc/autosummary.py, quartodoc/renderers/base.py, quartodoc/renderers/md_renderer.py, quartodoc/tests/test_renderers.py
This PR addresses
* #172 
by not escaping `[` or `]` in table descriptions.
=> fix: do not sanitize interlinks in table descriptions

quartodoc/autosummary.py
This PR fixes the sidebar yaml to make our side entry a list. Let's wait and see the response to https://github.com/quarto-dev/quarto-cli/issues/5689, before potentially adding a dummy id entry / seeing if we should be configuring the sidebar another way)
=> fix: correct sidebar structure

quartodoc/autosummary.py, quartodoc/tests/test_validation.py, quartodoc/validation.py
Started adding the YAML validation, but turns out QuartoDoc is a bit more complicated then my test case so I'm getting some confusing behavior.  What I recommend is that we pair program on some of the most hairy bits together.  
~One test fails on purpose - might be best if we pair on this @machow when you are back.   One error that is confusing for example is when I leave the `name` field out under `contents`, like this:~ EDIT I made those pass 😆 
@machow lets sync when you are back.  I made it kind of far but the key is adding lots and lots of tests I think
=> [WIP] Yaml validation

quartodoc/renderers/md_renderer.py
This PR consolidates code for rendering tables into a method `._render_table()`
=> refactor: _render_table method to conslidate code

quartodoc/builder/blueprint.py, quartodoc/tests/test_builder_blueprint.py
This PR addresses #159 , by adding a more specific error when an object can't be found during blueprinting.
E.g. including the sentence "Does an object with the path quartodoc.bbb.ccc exist?"
=> fix: better messaging when can't find an object

quartodoc/renderers/md_renderer.py, quartodoc/tests/test_renderers.py
Addresses an issue pointed out by @schloerke -- we are rendering annotations twice for attributes. This can cause issues like sanitizing twice, etc...
=> fix: do not render attribute annotations twice

.github/workflows/ci.yml, quartodoc/renderers/md_renderer.py
It is nice to differentiate more when displaying the default function param value.
Before:
With PR:
=> Use italics when rendering a "required" default value

setup.cfg
This PR pins us to pydantic v1, while we work out backwards compatibility in #211
=> dev: pin pydantic to v1

Makefile, docs/get-started/basic-building.qmd, docs/get-started/overview.qmd, pyproject.toml, quartodoc/__main__.py, setup.cfg
- Added `--watch` command to `quartodoc build`
- Added help strings to the `quartodoc` CLI so end users can see docs for all the options when calling `quartodoc build --help`
=> add `--watch` flag to `quartodoc build`

.pre-commit-config.yaml, Makefile, docs/_quarto.yml, examples/auto-package/_quarto.yml, quartodoc/__init__.py, quartodoc/autosummary.py, quartodoc/builder/blueprint.py, quartodoc/layout.py, quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/example_class.py, quartodoc/tests/test_builder_blueprint.py, quartodoc/tests/test_renderers.py, setup.cfg
This PR addresses #158, by autogenerating site content, when no `sections:` are specified.
For example, this config...
```
quartodoc:
package: quartodoc
```
Will cause `quartodoc build` to produce a basic website, based on the top-level quartodoc module, with this message:
```
Autogenerating contents (since no contents specified in config)
Use the following configuration to recreate the automatically generated site:
package: quartodoc
sections:
- contents:
- name: get_function
- name: get_object
- name: Builder
- name: MdRenderer
- name: convert_inventory
- name: create_inventory
- name: preview
- name: blueprint
- name: collect
- name: Auto
desc: quartodoc is a package for building delightful python API documentation.
title: quartodoc
```
edit:
It also addresses …
=> Feat automodule

quartodoc/builder/blueprint.py, quartodoc/layout.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/example.py, quartodoc/tests/example_class.py
This PR adds the option `include_empty` to Auto, which specifies whether to include members with no docstring. It defaults to False, so members with empty docstrings are excluded.
=> Feat undoc empty

docs/get-started/docstring-examples.qmd
=> docs: example code block notes

docs/_quarto.yml, docs/get-started/basic-content.qmd, docs/get-started/basic-docs.qmd, docs/styles.css, quartodoc/autosummary.py, quartodoc/layout.py, quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_builder.ambr, quartodoc/tests/test_builder.py, quartodoc/tests/test_layout.py, quartodoc/tests/test_renderers.py, quartodoc/tests/test_validation.py
This PR address #183, by enabling users to create subtitles in their config. It also supports the encouraged workflow in pkgdown, where an entry might be only a title, or subtitle.
e.g.
```yaml
sections:
- title: a title
- subtitle: a subtitle
- contents:
- abc
- def
```
TODO:
=> feat: add subtitle option to section

quartodoc/autosummary.py, quartodoc/tests/example_dynamic.py, quartodoc/tests/test_basic.py
This PR addresses https://github.com/machow/plotnine-docs-demo/issues/18. Basically, when a user uses dynamic loading, we try to infer the canonical path to the object, using the object's `__module__` attribute (if it has one). This often works for classes and functions, but for values, or instances, generally does not do what you want.
This PR bails out of this behavior if the object isn't a class or function.
Note that sphinx's `automodule`, `autofunction`, `autoattribute` provides users with helpful levers around this behavior, since you wouldn't expect `autoattribute` to even attempt this. Because we just use Auto, we are currently stuck trying to infer the right behavior from the object itself.
=> Fix dynamic load

pyproject.toml
Replace exact version pin with an upper bound (until we work out backwards compat for griffe.expression changes)
=> dev: use upper bound for griffe version

quartodoc/autosummary.py, quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/example_docstring_styles.py, quartodoc/tests/test_renderers.py
Addresses https://github.com/machow/quartodoc/issues/241 by documenting the Builder's "parser" option, and adding basic snapshot tests of the 3 docstring styles.
=> Doc builder parser arg

quartodoc/autosummary.py, quartodoc/builder/blueprint.py, quartodoc/parsers.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/example_docstring_styles.py, quartodoc/tests/test_renderers.py
Addresses #248, by setting default `docstring_options` in the griffe loader.
=> feat: allow single  blank line in numpydoc parameter docstrings

docs/get-started/basic-content.qmd, quartodoc/autosummary.py, quartodoc/builder/blueprint.py, quartodoc/layout.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/example_class.py, quartodoc/tests/test_builder.py, quartodoc/tests/test_builder_blueprint.py
Addresses #235, by adding include_attributes, include_classes, include_functions options for `Auto`. These determine whether or not to filter members of the corresponding kind.
Address #239, by adding include_inherited option. This gets members from `obj.all_members` (and when set, does not filter out alias objects).
=> Feat include filters

_extensions/interlinks/interlinks.lua
Types such as `dict` and `list` in the python standard library appear multiple times in the inventory. For example, for `dict`, there is the standard library https://docs.python.org/3.10/library/stdtypes.html#dict (the one we want), but also more obscure matches like https://docs.python.org/3.10/library/2to3.html?highlight=dict#to3fixer-dict.
Luckily, the `stdtypes` matches come up first. There is no guaranty for this, but I think it is fine to still link the first match and log a warning instead of not linking them.
While I was at it, I also made the module local functions local, renamed the `inventory` variable in the for loop to not shadow the global `inventory` and replaced deprecated `quarto.utils` functions with the appropriate `quarto.log` functions (had to get rid of those …
=> feat(interlinks): filter on py domain by default

_extensions/interlinks/_extension.yml, _extensions/interlinks/interlinks.lua, docs/get-started/interlinks.qmd, quartodoc/__main__.py, quartodoc/autosummary.py
This PR addresses #249 , by adding a "fast" mode via the `quartodoc interlinks --fast` command.
* this command generates inventory files as plain text (e.g. objects_python.txt) rather than json
* when it detects a `.txt` file, the lua filter will parse that using regexes inspired by https://github.com/bskinn/sphobjinv/blob/main/src/sphobjinv/re.py
This should cut parse time to about 1/5th what it was. Note that the package being generated still produces a json inventory. I think we eventually should swap that out with json (and move it into `_inv`, and later the `.quartodoc` scratchpad folder).
=> Feat interlinks fast

quartodoc/builder/blueprint.py, quartodoc/layout.py, quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/test_basic.py, quartodoc/tests/test_builder_blueprint.py, quartodoc/tests/test_renderers.py
addresses #226 by adding two options to Auto:
* `signature_path`: whether to show the full, relative, or short name for a function.
* `member_options`: Auto options to set on members
Note that there were a number of changes necessary to enable these options:
* Because the renderer generates signatures directly from griffe objects, but we set signature_path on layout.Doc, we needed to temporarily set signature_path on the renderer, prior to rendering.
* I cleaned up how quartodoc detects options specified on Auto (in `_non_default_fields()`), so we can get back exactly the arguments a user passed to initiate auto or options.
=> feat: add Auto signature_path and member_options fields

quartodoc/builder/blueprint.py, quartodoc/tests/test_builder_blueprint.py
This PR fixes a bug where setting member_options in options, caused package and dynamic to be set back to their default values on the members
```python
from quartodoc import blueprint, Builder
cfg = yaml.safe_load("""
quartodoc:
package: quartodoc
options:
member_options:
signature_name: "short"
sections:
- contents:
- MdRenderer
"""
builder = Builder.from_quarto_cfg(cfg)
blueprint(builder)
```
Caused the error:
```python
WorkaroundKeyError: Cannot find an object named: render_header. Does an object with the path quartodoc:render_header exist?
```
Since it unset package from `quartodoc.MdRenderer`, and fell back on the default package `quartodoc` (in the top-level config).
The gist is that blueprint uses a function called `_non_default_entries` to get only the arguments manually specified …
=> fix: setting member_options no longer unsets package on members

_extensions/interlinks/interlinks.lua
Encountered this when running `quarto preview` without having first generated API documentation with `quartodoc`
=> fix(interlinks): ensure that json fixup only happens when json is not nil

.devcontainer.json, Dockerfile
Addresses #251, replaces #252
Modify the following aspects of the previous container:
- Only had the root user in the container, causing permission issues when run locally.
- The version of Quarto CLI was hard coded and the new version could not be installed without updating the file.
- Arm64 support lacks.
- Dockerfile had to be included in the repository.
=> Update devcontainer config

quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/example_class.py, quartodoc/tests/test_builder_blueprint.py
Addresses #270, by removing parameters named "self" or "cls" from function signatures, when...
* the functions are on a class
* the matching parameter is the first one in the signature
=> Fix no render self

_extensions/interlinks/interlinks.lua
This PR ensures that the filter does not produce an error under these conditions:
* a user adds the interlinks filter, but
* does not have an `interlinks:` config in their `_quarto.yml`
This is useful for people adding interlinks internally within a package, without wanting to add any external inventories.
=> fix(interlinks): do not error if no config found

quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/example.py, quartodoc/tests/example_alias_target.py, quartodoc/tests/example_alias_target__nested.py, quartodoc/tests/test_builder_blueprint.py, quartodoc/tests/test_renderers.py
=> Fix signature when alias

quartodoc/autosummary.py, quartodoc/tests/example_star_imports.py, quartodoc/tests/test_builder_blueprint.py
It appears that when a class is star imported, then when its members are dynamically loaded, they may have issues fetching the class. I resolved by setting it so that when a method is being dynamically loaded, it also tries to dynamically load its parent.
=> fix: dynamic child should load parent dynamically

docs/get-started/basic-content.qmd, quartodoc/layout.py
This PR documents the signature_name argument, which controls how much of an objects name to show in its signature. E.g.
* relative (default): whatever the user specified as the `name:` argument
* full: the full path to the object
* short: just the object name (i.e. no periods)
=> docs: add signature_name to docstring and all content options section

README.md, docs/GITHUB.qmd, docs/get-started/overview.qmd
This PR takes @hamelsmu 's work in #261 and adds the CI badge to our github readme. Since we now generate the readme based on the quartodoc homepage (overview.qmd), I added it there!
Note that I had to add a title to our `GITHUB.qmd` to work around a strange quarto bug (https://github.com/quarto-dev/quarto-cli/issues/7157), but the title set there doesn't apply (since quarto uses the title from the included document by design).
=> docs: add ci badge

quartodoc/ast.py, quartodoc/tests/test_ast.py
Addresses #283 by ensuring we always preserve text that is above a header, when transforming parsed docstrings.
TODO:
=> fix: ensure docstring section transform preserves starting text

.github/workflows/ci.yml, pyproject.toml, quartodoc/__main__.py, quartodoc/_pydantic_compat.py, quartodoc/ast.py, quartodoc/autosummary.py, quartodoc/builder/_node.py, quartodoc/builder/blueprint.py, quartodoc/builder/utils.py, quartodoc/interlinks.py, quartodoc/layout.py, quartodoc/tests/__snapshots__/test_validation.ambr, quartodoc/tests/test_ast.py, quartodoc/tests/test_layout.py, quartodoc/tests/test_validation.py, quartodoc/validation.py
This PR addresses #209, by using `pydantic.v1` to kick the can down the road. This approach seems to be much easier to do for now, as writing v1 and v2 compatible code requires a lot of tricky moves (e.g. handling the `__root__` change, etc..).
=> Dev pydantic compat

quartodoc/__main__.py, quartodoc/tests/test_cli.py
Restores the behavior of changing the working directory to the one holding `_quarto.yml`. I don't think this is ideal, but also not a huge issue. We still put the original directory on sys.path if we change directories, so people relying on importing from the cwd should still get that behavior.
=> fix: restore chdir behavior, add test

quartodoc/builder/blueprint.py, quartodoc/tests/example_alias_target.py, quartodoc/tests/example_alias_target__nested.py, quartodoc/tests/test_builder_blueprint.py
This PR adds support for importing functions from other packages as members. 
Previously, when documenting an entire module -- if a function was directly imported from another package into a module of interest, then it worked. However, if the import was indirect, it would fail.
I also made the following tweaks:
* respect `__all__` when getting the initial module members (these may still be filtered based on options like `include_attributes`)
* don't always rule out members when they're from external packages
=> fix: resolve external alias members via loading

docs/get-started/docstring-style.qmd
Documents how to configure sphinx and google style docstrings. (Previously, the section said only numpy was supported).
=> docs: configuring docstring styles

quartodoc/__main__.py
It looks like in https://github.com/machow/quartodoc/pull/297, I reverted to the original behavior of changing directories to where `_quarto.yml` lives, but did not append the cwd to `sys.path` before switching.
=> fix: really add cwd to sys path this time

pyproject.toml, quartodoc/renderers/md_renderer.py, quartodoc/tests/test_renderers.py
BREAKING CHANGE: This commit may break renderers implemented by
downstream users if they use the `griffe.expressions` module.
Over the past 8 months (and about 10 releases), griffe has had
2 releases that have broken quartodoc. So the griffe requirement
is set to include only the current known working versions.
=> chore: bump griffe to >=0.33, <=0.38

quartodoc/autosummary.py, quartodoc/tests/example_alias_target.py, quartodoc/tests/test_basic.py
This PR allows for dynamically documenting methods defined like...
```python
from some_module import some_func
class SomeClass:
some_method = some_func
```
I refactored the approach we use to look for the canonical path to an object. Previously, it wasn't always finding where the dynamic objects lived, and so resulted in returning something closer to the static result. This means that in the above case it believed some_method was an attribute.
I moved the logic for looking for where an object lives into `_canonical_path`, so hopefully it is easier to add and test new cases.
=> fix: get_object dynamic supports methods set by assignments

quartodoc/autosummary.py, quartodoc/tests/example_dynamic.py, quartodoc/tests/test_basic.py
This PR addresses https://github.com/machow/quartodoc/issues/307, by ensuring we can (again) dynamically load value-less attributes off of classes and modules.
It contains additional tests for
* `_canonical_path()` - the function that attempts to go from <some_object> -> its canonical path (i.e. the submodule in which it is defined)
* `get_object(..., dynamic=True)` for more cases
See also https://github.com/machow/quartodoc/issues/308 for a proposal to improve how we get docstrings for instances.
=> Fix dynamic load members

Makefile, quartodoc/ast.py, quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/example_docstring_styles.py
This PR enables support for the latest version of griffe. It also fixes a small bug quartodoc's own API docs, by disabling plum's docstring enhancements.
=> fix: compatibility with griffe 0.39

quartodoc/pandoc/blocks.py, quartodoc/pandoc/inlines.py, quartodoc/tests/pandoc/test_blocks.py, quartodoc/tests/pandoc/test_inlines.py
InlineContent is already processed recursively, this
change makes the type definition recursive too.
And it also defines a clearer relationship between InlineContent
and BlockContent.
=> Define pandoc InlineContent type to be recursive

docs/get-started/basic-content.qmd
I found the work around for how to use the `source_dir` option correctly in this old issue: https://github.com/machow/quartodoc/issues/130.
I didn't understand how to use it through the docs so this PR adds an example to the docs.
Not sure if it is in the right place, so feel free to move it. I found `quartodoc` really helpful and easy to use (once I managed to find the above issue) to document a Python project that didn't end up as a package.
=> Add docs for how to document only Python files

quartodoc/builder/blueprint.py, quartodoc/tests/example_alias_target.py, quartodoc/tests/example_alias_target__nested.py, quartodoc/tests/test_builder_blueprint.py
Addresses #317 by ensuring we include methods defined in a class, even we are documenting an alias of that class.
=> fix: do not exclude child methods on alias classes

pyproject.toml
This is a temporary patch to fix CI runs. It pins pytest to be <8.0.0.
Seems like the long term fix is likely here:
https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#tests-as-part-of-application-code
Here is the error encountered on test collection:
```
_________________ ERROR collecting quartodoc/tests/test_ast.py _________________
import file mismatch:
imported module 'quartodoc.tests.test_ast' has this __file__ attribute:
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/quartodoc/tests/test_ast.py
which is not the same as the test file we want to collect:
/home/runner/work/quartodoc/quartodoc/quartodoc/tests/test_ast.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
```
=> dev: pin pytest<8.0.0

quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/example_signature.py, quartodoc/tests/test_ast.py, quartodoc/tests/test_builder_blueprint.py, quartodoc/tests/test_renderers.py
=> fix: duplicate names in annotations

docs/_quarto.yml, docs/get-started/interlinks.qmd, docs/objects-test.txt, quartodoc/__main__.py, quartodoc/interlinks.py, quartodoc/tests/test_interlinks.py
This PR provides a fix that allows a quartodoc site to use the objects.txt file generated by another site. an objects.txt file is an unzipped version of objects.inv, and is also [supported by sphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#configuration). 
~Blocked by: https://github.com/quarto-dev/quarto-cli/issues/10021~ I'm just going to push it since it should only be an issue on preview branches.
=> docs: use fast interlinks

docs/examples/index.qmd
Switch `Shinyswatch` from using `rstudio` to `posit-dev` to avoid a 404
=> Fix Shinyswatch url in examples

pyproject.toml
requests is being imported in `interlinks.py` in the latest release but it isn't listed as a dependency
=> chore(deps): add missing requests dependency

.github/workflows/ci.yml, case_studies/parsing.qmd, docs/get-started/basic-content.qmd, docs/get-started/dev-renderers.qmd, docs/get-started/extending.qmd, docs/get-started/sidebar.qmd, pyproject.toml, quartodoc/_griffe_compat.py, quartodoc/ast.py, quartodoc/autosummary.py, quartodoc/builder/blueprint.py, quartodoc/inventory.py, quartodoc/layout.py, quartodoc/renderers/md_renderer.py, quartodoc/tests/test_ast.py, quartodoc/tests/test_basic.py, quartodoc/tests/test_builder_blueprint.py, quartodoc/tests/test_renderers.py
This PR adds support for griffe v1, by attempting to do v1-centered imports. If that fails, it falls back to imports that expect griffe < v1.
Note that auto package functionality requires griffe > v0.46.0, which renamed `member_is_exported` to `is_exported`.
=> fix: support griffe v1, and backwards compat to v0.37.0

quartodoc/tests/example_stubs.py, quartodoc/tests/example_stubs.pyi, quartodoc/tests/test_basic.py
This PR verifies that quartodoc loads type annotations from stub files (.pyi) when present. Note that this may require a specific version of griffe, like v1+ (which is doing all the heavy lifting ;)
=> tests: get_object returns annotations from pyi stub files

docs/_quarto.yml, docs/get-started/overview.qmd, docs/styles-quartodoc.css, pyproject.toml, quartodoc/autosummary.py, quartodoc/renderers/base.py, quartodoc/renderers/md_renderer.py, quartodoc/static/styles.css, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/test_renderers.py
This PR implements description lists, based on the way [py-shiny](https://shiny.posit.co/py/api/ui.page_sidebar.html) and [plotnine](https://has2k1.github.io/plotnine/reference/) extended the renderer in their docs.
While in the Renderer, I'll work on...
* migrating to use the `quartodoc.pandoc` submodule.
* consolidate more header generation into the .render_header() method.
* planning out nice HTML classes, so it's easier to style everything
Backwards incompatible changes:
* `render(self, dc.Object | dc.Alias)` now calls `render(self, dc.Docstring)`, rather than iterating over the docstring itself.
- This makes the printout of dc.Docstring renders in snapshot tests look a bit nicer. 
Here's a rough sketch of the HTML structure rendered by quarto, using PUG:
```pug
// Doc example for …
```
=> feat!: initial description-list support; render_header cleanup

quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_renderers.ambr
This PR fixes a bug in the unreleased description-list param table rendering. When a parameter had no default, it was erroneously rendered as being set to the a default of `None`.
=> fix: parameter description list do not render None as default

quartodoc/builder/blueprint.py, quartodoc/layout.py, quartodoc/tests/test_builder_blueprint.py
This PR adds a `member_order` argument to Auto that decides how members should be sorted. There are two options:
* `"alphabetical"`: sorted alphabetically (e.g. a first, z last)
* `"source"`: in order they appear in the source code
=> feat: add Auto member_order option

.github/workflows/ci.yml, quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_renderers.ambr, quartodoc/tests/example_signature.py
This PR addresses #361 by adding a missing branch, when rendering annotations. (~TODO: add a test~)
=> fix: missing branch in show_signature_annotations

quartodoc/builder/blueprint.py, quartodoc/layout.py, quartodoc/tests/test_builder_blueprint.py
This PR implements the exclude option for documenting items. This option is currently documented, but marked unimplemented.
=> feat: implement auto excludes option

Makefile, docs/get-started/sidebar.qmd
This PR fixes the preview of the sidebar yaml on the sidebar guide page (previously the raw include directive appeared)
=> docs: fix sidebar preview and collapse

quartodoc/renderers/md_renderer.py, quartodoc/tests/__snapshots__/test_renderers.ambr
This PR fixes the signature, to include trailing commas after parameters. Here's an example of a fixed signature from our docs:
=> Fix: add trailing commas to multiline signature

.github/workflows/ci.yml, Makefile, README.md, docs/get-started/overview.qmd, scripts/build_tmp_starter.py
This PR addresses an issue flagged by @chendaniely -- the intro snippet produces errors.
Note that one important piece here is that the github readme is generated from the quartodoc homepage (currently https://machow.github.io/quartodoc/get-started/overview.html). But this hadn't been regenerated to reflect the latest there.
I don't love how verbose the intro snippet is now, but let's just get it working in this PR. I think there are some nice ways to streamline things down the road!
TODO: add a test of the intro snippet
=> docs: regenerate gh readme

_extensions/interlinks/interlinks.lua, _extensions/interlinks/objects.txt, _extensions/interlinks/test.qmd, docs/_quarto.yml, docs/get-started/crossrefs.qmd, docs/get-started/interlinks-autolink.qmd, docs/get-started/interlinks.qmd
This WIP PR automatically formats code as interlinks. Addresses #328 
Essentially:
* interlinks now supports a `interlinks.autolinks = True` setting, that turns inline Code directly to links.
* This means you don't need to use ``[](`some_function`)`` syntax.
* Currently...
- No link shortening with `~`. I don't think it would be confusing for this approach.
- `~a.b.c` when interlinks still uses `~a.b.c` for the link text (use full link syntax for name shortening)
- `~a.b.c` when unmatched returns the original code `~a.b.c`
* Aliases
- set `interlinks.aliases` to allow linking functions like `quartodoc.Auto` by just writing `Auto`
* Opting out
- use the `.qd-no-link` class to tell quartodoc not to try interlinking. E.g. `` `my_func`{.qd-no-link} ``
**Alias example**
```
interlinks: …
```
=> feat: interlinks autolink
